### ISSUE TITLE
2nd schema won't import, functions / missing tables?

### ISSUE THREAD

**Issue by levellearning-admin** [ankane/pgsync#143]
I have schemas `hdb_catalog` and `public` in prod:
![image](https://user-images.githubusercontent.com/72838530/134617379-6e1528ed-4f89-4e68-b764-c8200d541cc9.png)

a yml file with the config:
![image](https://user-images.githubusercontent.com/72838530/134623368-e46c077c-4985-464b-8b75-94b8d568ff85.png)

I have tried all manner of --schema-first, --schema-only, --all-schemas, defer constraints.. I even grabbed `pg-diff` and ran it's schema compare to get raw SQL and pasted that with a similar problem. So I don't think this is pgsyncs problem exactly, but there _has_ to be a way right?

when I run sync to my local, empty db
```
✗ pgsync --schema-only --debug  --defer-constraints-v2
From: prod on prod.us-west-2.rds.amazonaws.com:5432
To: local on localhost:5432
[from] SELECT unnest(current_schemas(true)) AS schema
[from] SELECT table_schema AS schema, table_name AS table FROM information_schema.tables WHERE table_type = 'BASE TABLE' AND table_schema NOT IN ('information_schema', 'pg_catalog') ORDER BY 1, 2
[to] SELECT schema_name FROM information_schema.schemata ORDER BY 1
[to] CREATE SCHEMA "hdb_catalog"
pg_dump: last built-in OID is 16383
pg_dump: reading extensions
pg_dump: identifying extension members
pg_dump: reading schemas
pg_dump: reading user-defined tables
pg_dump: reading user-defined functions
pg_dump: reading user-defined types
pg_dump: reading procedural languages
pg_dump: reading user-defined aggregate functions
pg_dump: reading user-defined operators
pg_dump: reading user-defined access methods
pg_dump: reading user-defined operator classes
pg_dump: reading user-defined operator families
pg_dump: reading user-defined text search parsers
pg_dump: reading user-defined text search templates
pg_dump: reading user-defined text search dictionaries
pg_dump: reading user-defined text search configurations
pg_dump: reading user-defined foreign-data wrappers
pg_dump: reading user-defined foreign servers
pg_dump: reading default privileges
pg_dump: reading user-defined collations
pg_dump: reading user-defined conversions
pg_dump: reading type casts
pg_dump: reading transforms
pg_dump: reading table inheritance information
pg_dump: reading event triggers
pg_dump: finding extension tables
pg_dump: finding inheritance relationships
pg_dump: reading column info for interesting tables
pg_dump: finding the columns and types of table "hdb_catalog.event_invocation_logs"
pg_dump: finding default expressions of table "hdb_catalog.event_invocation_logs"
pg_dump: finding the columns and types of table "hdb_catalog.event_log"
pg_dump: finding default expressions of table "hdb_catalog.event_log"
pg_dump: finding the columns and types of table "hdb_catalog.hdb_action_log"
pg_dump: finding default expressions of table "hdb_catalog.hdb_action_log"
pg_dump: finding check constraints for table "hdb_catalog.hdb_action_log"
pg_dump: finding the columns and types of table "hdb_catalog.hdb_cron_event_invocation_logs"
pg_dump: finding default expressions of table "hdb_catalog.hdb_cron_event_invocation_logs"
pg_dump: finding the columns and types of table "hdb_catalog.hdb_cron_events"
pg_dump: finding default expressions of table "hdb_catalog.hdb_cron_events"
pg_dump: finding check constraints for table "hdb_catalog.hdb_cron_events"
pg_dump: finding the columns and types of table "hdb_catalog.hdb_metadata"
pg_dump: finding default expressions of table "hdb_catalog.hdb_metadata"
pg_dump: finding the columns and types of table "hdb_catalog.hdb_scheduled_event_invocation_logs"
pg_dump: finding default expressions of table "hdb_catalog.hdb_scheduled_event_invocation_logs"
pg_dump: finding the columns and types of table "hdb_catalog.hdb_scheduled_events"
pg_dump: finding default expressions of table "hdb_catalog.hdb_scheduled_events"
pg_dump: finding check constraints for table "hdb_catalog.hdb_scheduled_events"
pg_dump: finding the columns and types of table "hdb_catalog.hdb_schema_notifications"
pg_dump: finding default expressions of table "hdb_catalog.hdb_schema_notifications"
pg_dump: finding check constraints for table "hdb_catalog.hdb_schema_notifications"
pg_dump: finding the columns and types of table "hdb_catalog.hdb_version"
pg_dump: finding default expressions of table "hdb_catalog.hdb_version"
pg_dump: flagging inherited columns in subtables
pg_dump: reading indexes
pg_dump: reading indexes for table "hdb_catalog.event_invocation_logs"
pg_dump: reading indexes for table "hdb_catalog.event_log"
pg_dump: reading indexes for table "hdb_catalog.hdb_action_log"
pg_dump: reading indexes for table "hdb_catalog.hdb_cron_event_invocation_logs"
pg_dump: reading indexes for table "hdb_catalog.hdb_cron_events"
pg_dump: reading indexes for table "hdb_catalog.hdb_metadata"
pg_dump: reading indexes for table "hdb_catalog.hdb_scheduled_event_invocation_logs"
pg_dump: reading indexes for table "hdb_catalog.hdb_scheduled_events"
pg_dump: reading indexes for table "hdb_catalog.hdb_schema_notifications"
pg_dump: reading indexes for table "hdb_catalog.hdb_version"
pg_dump: flagging indexes in partitioned tables
pg_dump: reading extended statistics
pg_dump: reading constraints
pg_dump: reading foreign key constraints for table "hdb_catalog.event_invocation_logs"
pg_dump: reading foreign key constraints for table "hdb_catalog.event_log"
pg_dump: reading foreign key constraints for table "hdb_catalog.hdb_cron_event_invocation_logs"
pg_dump: reading foreign key constraints for table "hdb_catalog.hdb_cron_events"
pg_dump: reading foreign key constraints for table "hdb_catalog.hdb_scheduled_event_invocation_logs"
pg_dump: reading foreign key constraints for table "hdb_catalog.hdb_scheduled_events"
pg_dump: reading triggers
pg_dump: reading triggers for table "hdb_catalog.event_invocation_logs"
pg_dump: reading triggers for table "hdb_catalog.event_log"
pg_dump: reading triggers for table "hdb_catalog.hdb_cron_event_invocation_logs"
pg_dump: reading triggers for table "hdb_catalog.hdb_cron_events"
pg_dump: reading triggers for table "hdb_catalog.hdb_scheduled_event_invocation_logs"
pg_dump: reading triggers for table "hdb_catalog.hdb_scheduled_events"
pg_dump: reading rewrite rules
pg_dump: reading policies
pg_dump: reading row security enabled for table "hdb_catalog.event_invocation_logs"
pg_dump: reading policies for table "hdb_catalog.event_invocation_logs"
pg_dump: reading row security enabled for table "hdb_catalog.event_log"
pg_dump: reading policies for table "hdb_catalog.event_log"
pg_dump: reading row security enabled for table "hdb_catalog.hdb_action_log"
pg_dump: reading policies for table "hdb_catalog.hdb_action_log"
pg_dump: reading row security enabled for table "hdb_catalog.hdb_cron_event_invocation_logs"
pg_dump: reading policies for table "hdb_catalog.hdb_cron_event_invocation_logs"
pg_dump: reading row security enabled for table "hdb_catalog.hdb_cron_events"
pg_dump: reading policies for table "hdb_catalog.hdb_cron_events"
pg_dump: reading row security enabled for table "hdb_catalog.hdb_metadata"
pg_dump: reading policies for table "hdb_catalog.hdb_metadata"
pg_dump: reading row security enabled for table "hdb_catalog.hdb_scheduled_event_invocation_logs"
pg_dump: reading policies for table "hdb_catalog.hdb_scheduled_event_invocation_logs"
pg_dump: reading row security enabled for table "hdb_catalog.hdb_scheduled_events"
pg_dump: reading policies for table "hdb_catalog.hdb_scheduled_events"
pg_dump: reading row security enabled for table "hdb_catalog.hdb_schema_notifications"
pg_dump: reading policies for table "hdb_catalog.hdb_schema_notifications"
pg_dump: reading row security enabled for table "hdb_catalog.hdb_version"
pg_dump: reading policies for table "hdb_catalog.hdb_version"
pg_dump: reading publications
pg_dump: reading publication membership
pg_dump: reading publication membership for table "hdb_catalog.event_invocation_logs"
pg_dump: reading publication membership for table "hdb_catalog.event_log"
pg_dump: reading publication membership for table "hdb_catalog.hdb_action_log"
pg_dump: reading publication membership for table "hdb_catalog.hdb_cron_event_invocation_logs"
pg_dump: reading publication membership for table "hdb_catalog.hdb_cron_events"
pg_dump: reading publication membership for table "hdb_catalog.hdb_metadata"
pg_dump: reading publication membership for table "hdb_catalog.hdb_scheduled_event_invocation_logs"
pg_dump: reading publication membership for table "hdb_catalog.hdb_scheduled_events"
pg_dump: reading publication membership for table "hdb_catalog.hdb_schema_notifications"
pg_dump: reading publication membership for table "hdb_catalog.hdb_version"
pg_dump: reading subscriptions
pg_dump: reading dependency data
pg_dump: saving encoding = UTF8
pg_dump: saving standard_conforming_strings = on
pg_dump: saving search_path =
pg_dump: saving database definition
pg_restore: connecting to database for restore
pg_restore: dropping FK CONSTRAINT hdb_scheduled_event_invocation_logs hdb_scheduled_event_invocation_logs_event_id_fkey
pg_restore: dropping FK CONSTRAINT hdb_cron_event_invocation_logs hdb_cron_event_invocation_logs_event_id_fkey
pg_restore: dropping FK CONSTRAINT event_invocation_logs event_invocation_logs_event_id_fkey
pg_restore: dropping INDEX hdb_version_one_row
pg_restore: dropping INDEX hdb_scheduled_event_status
pg_restore: dropping INDEX hdb_cron_events_unique_scheduled
pg_restore: dropping INDEX hdb_cron_event_status
pg_restore: dropping INDEX event_log_trigger_name_idx
pg_restore: dropping INDEX event_log_locked_idx
pg_restore: dropping INDEX event_log_delivered_idx
pg_restore: dropping INDEX event_log_created_at_idx
pg_restore: dropping INDEX event_invocation_logs_event_id_idx
pg_restore: dropping CONSTRAINT hdb_version hdb_version_pkey
pg_restore: dropping CONSTRAINT hdb_schema_notifications hdb_schema_notifications_pkey
pg_restore: dropping CONSTRAINT hdb_scheduled_events hdb_scheduled_events_pkey
pg_restore: dropping CONSTRAINT hdb_scheduled_event_invocation_logs hdb_scheduled_event_invocation_logs_pkey
pg_restore: dropping CONSTRAINT hdb_metadata hdb_metadata_resource_version_key
pg_restore: dropping CONSTRAINT hdb_metadata hdb_metadata_pkey
pg_restore: dropping CONSTRAINT hdb_cron_events hdb_cron_events_pkey
pg_restore: dropping CONSTRAINT hdb_cron_event_invocation_logs hdb_cron_event_invocation_logs_pkey
pg_restore: dropping CONSTRAINT hdb_action_log hdb_action_log_pkey
pg_restore: dropping CONSTRAINT event_log event_log_pkey
pg_restore: dropping CONSTRAINT event_invocation_logs event_invocation_logs_pkey
pg_restore: dropping TABLE hdb_version
pg_restore: dropping TABLE hdb_schema_notifications
pg_restore: dropping TABLE hdb_scheduled_events
pg_restore: dropping TABLE hdb_scheduled_event_invocation_logs
pg_restore: dropping TABLE hdb_metadata
pg_restore: dropping TABLE hdb_cron_events
pg_restore: dropping TABLE hdb_cron_event_invocation_logs
pg_restore: dropping TABLE hdb_action_log
pg_restore: dropping TABLE event_log
pg_restore: dropping TABLE event_invocation_logs
pg_restore: creating TABLE "hdb_catalog.event_invocation_logs"
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 208; 1259 100797 TABLE event_invocation_logs postgres
pg_restore: error: could not execute query: ERROR:  function hdb_catalog.gen_hasura_uuid() does not exist
LINE 2:     id text DEFAULT hdb_catalog.gen_hasura_uuid() NOT NULL,
                            ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Command was: CREATE TABLE hdb_catalog.event_invocation_logs (
    id text DEFAULT hdb_catalog.gen_hasura_uuid() NOT NULL,
    event_id text,
    status integer,
    request json,
    response json,
    created_at timestamp without time zone DEFAULT now()
);


pg_restore: creating TABLE "hdb_catalog.event_log"
pg_restore: from TOC entry 209; 1259 100805 TABLE event_log postgres
pg_restore: error: could not execute query: ERROR:  function hdb_catalog.gen_hasura_uuid() does not exist
LINE 2:     id text DEFAULT hdb_catalog.gen_hasura_uuid() NOT NULL,
                            ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Command was: CREATE TABLE hdb_catalog.event_log (
    id text DEFAULT hdb_catalog.gen_hasura_uuid() NOT NULL,
    schema_name text NOT NULL,
    table_name text NOT NULL,
    trigger_name text NOT NULL,
    payload jsonb NOT NULL,
    delivered boolean DEFAULT false NOT NULL,
    error boolean DEFAULT false NOT NULL,
    tries integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    locked timestamp with time zone,
    next_retry_at timestamp without time zone,
    archived boolean DEFAULT false NOT NULL
);


pg_restore: creating TABLE "hdb_catalog.hdb_action_log"
pg_restore: from TOC entry 210; 1259 100817 TABLE hdb_action_log postgres
pg_restore: error: could not execute query: ERROR:  function hdb_catalog.gen_hasura_uuid() does not exist
LINE 2:     id uuid DEFAULT hdb_catalog.gen_hasura_uuid() NOT NULL,
                            ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Command was: CREATE TABLE hdb_catalog.hdb_action_log (
    id uuid DEFAULT hdb_catalog.gen_hasura_uuid() NOT NULL,
    action_name text,
    input_payload jsonb NOT NULL,
    request_headers jsonb NOT NULL,
    session_variables jsonb NOT NULL,
    response_payload jsonb,
    errors jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    response_received_at timestamp with time zone,
    status text NOT NULL,
    CONSTRAINT hdb_action_log_status_check CHECK ((status = ANY (ARRAY['created'::text, 'processing'::text, 'completed'::text, 'error'::text])))
);


pg_restore: creating TABLE "hdb_catalog.hdb_cron_event_invocation_logs"
pg_restore: from TOC entry 211; 1259 100826 TABLE hdb_cron_event_invocation_logs postgres
pg_restore: error: could not execute query: ERROR:  function hdb_catalog.gen_hasura_uuid() does not exist
LINE 2:     id text DEFAULT hdb_catalog.gen_hasura_uuid() NOT NULL,
                            ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Command was: CREATE TABLE hdb_catalog.hdb_cron_event_invocation_logs (
    id text DEFAULT hdb_catalog.gen_hasura_uuid() NOT NULL,
    event_id text,
    status integer,
    request json,
    response json,
    created_at timestamp with time zone DEFAULT now()
);


pg_restore: creating TABLE "hdb_catalog.hdb_cron_events"
pg_restore: from TOC entry 212; 1259 100834 TABLE hdb_cron_events postgres
pg_restore: error: could not execute query: ERROR:  function hdb_catalog.gen_hasura_uuid() does not exist
LINE 2:     id text DEFAULT hdb_catalog.gen_hasura_uuid() NOT NULL,
                            ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Command was: CREATE TABLE hdb_catalog.hdb_cron_events (
    id text DEFAULT hdb_catalog.gen_hasura_uuid() NOT NULL,
    trigger_name text NOT NULL,
    scheduled_time timestamp with time zone NOT NULL,
    additional_payload json,
    status text DEFAULT 'scheduled'::text NOT NULL,
    tries integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    next_retry_at timestamp with time zone,
    CONSTRAINT valid_status CHECK ((status = ANY (ARRAY['scheduled'::text, 'locked'::text, 'delivered'::text, 'error'::text, 'dead'::text])))
);


pg_restore: creating TABLE "hdb_catalog.hdb_metadata"
pg_restore: creating TABLE "hdb_catalog.hdb_scheduled_event_invocation_logs"
pg_restore: from TOC entry 214; 1259 100852 TABLE hdb_scheduled_event_invocation_logs postgres
pg_restore: error: could not execute query: ERROR:  function hdb_catalog.gen_hasura_uuid() does not exist
LINE 2:     id text DEFAULT hdb_catalog.gen_hasura_uuid() NOT NULL,
                            ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Command was: CREATE TABLE hdb_catalog.hdb_scheduled_event_invocation_logs (
    id text DEFAULT hdb_catalog.gen_hasura_uuid() NOT NULL,
    event_id text,
    status integer,
    request json,
    response json,
    created_at timestamp with time zone DEFAULT now()
);


pg_restore: creating TABLE "hdb_catalog.hdb_scheduled_events"
pg_restore: from TOC entry 215; 1259 100860 TABLE hdb_scheduled_events postgres
pg_restore: error: could not execute query: ERROR:  function hdb_catalog.gen_hasura_uuid() does not exist
LINE 2:     id text DEFAULT hdb_catalog.gen_hasura_uuid() NOT NULL,
                            ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Command was: CREATE TABLE hdb_catalog.hdb_scheduled_events (
    id text DEFAULT hdb_catalog.gen_hasura_uuid() NOT NULL,
    webhook_conf json NOT NULL,
    scheduled_time timestamp with time zone NOT NULL,
    retry_conf json,
    payload json,
    header_conf json,
    status text DEFAULT 'scheduled'::text NOT NULL,
    tries integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    next_retry_at timestamp with time zone,
    comment text,
    CONSTRAINT valid_status CHECK ((status = ANY (ARRAY['scheduled'::text, 'locked'::text, 'delivered'::text, 'error'::text, 'dead'::text])))
);


pg_restore: creating TABLE "hdb_catalog.hdb_schema_notifications"
pg_restore: creating TABLE "hdb_catalog.hdb_version"
pg_restore: from TOC entry 217; 1259 100880 TABLE hdb_version postgres
pg_restore: error: could not execute query: ERROR:  function hdb_catalog.gen_hasura_uuid() does not exist
LINE 2:     hasura_uuid uuid DEFAULT hdb_catalog.gen_hasura_uuid() N...
                                     ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Command was: CREATE TABLE hdb_catalog.hdb_version (
    hasura_uuid uuid DEFAULT hdb_catalog.gen_hasura_uuid() NOT NULL,
    version text NOT NULL,
    upgraded_on timestamp with time zone NOT NULL,
    cli_state jsonb DEFAULT '{}'::jsonb NOT NULL,
    console_state jsonb DEFAULT '{}'::jsonb NOT NULL
);


pg_restore: creating CONSTRAINT "hdb_catalog.event_invocation_logs event_invocation_logs_pkey"
pg_restore: from TOC entry 4757; 2606 103474 CONSTRAINT event_invocation_logs event_invocation_logs_pkey postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.event_invocation_logs" does not exist
Command was: ALTER TABLE ONLY hdb_catalog.event_invocation_logs
    ADD CONSTRAINT event_invocation_logs_pkey PRIMARY KEY (id);


pg_restore: creating CONSTRAINT "hdb_catalog.event_log event_log_pkey"
pg_restore: from TOC entry 4762; 2606 103476 CONSTRAINT event_log event_log_pkey postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.event_log" does not exist
Command was: ALTER TABLE ONLY hdb_catalog.event_log
    ADD CONSTRAINT event_log_pkey PRIMARY KEY (id);


pg_restore: creating CONSTRAINT "hdb_catalog.hdb_action_log hdb_action_log_pkey"
pg_restore: from TOC entry 4765; 2606 103478 CONSTRAINT hdb_action_log hdb_action_log_pkey postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.hdb_action_log" does not exist
Command was: ALTER TABLE ONLY hdb_catalog.hdb_action_log
    ADD CONSTRAINT hdb_action_log_pkey PRIMARY KEY (id);


pg_restore: creating CONSTRAINT "hdb_catalog.hdb_cron_event_invocation_logs hdb_cron_event_invocation_logs_pkey"
pg_restore: from TOC entry 4767; 2606 103480 CONSTRAINT hdb_cron_event_invocation_logs hdb_cron_event_invocation_logs_pkey postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.hdb_cron_event_invocation_logs" does not exist
Command was: ALTER TABLE ONLY hdb_catalog.hdb_cron_event_invocation_logs
    ADD CONSTRAINT hdb_cron_event_invocation_logs_pkey PRIMARY KEY (id);


pg_restore: creating CONSTRAINT "hdb_catalog.hdb_cron_events hdb_cron_events_pkey"
pg_restore: from TOC entry 4770; 2606 103482 CONSTRAINT hdb_cron_events hdb_cron_events_pkey postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.hdb_cron_events" does not exist
Command was: ALTER TABLE ONLY hdb_catalog.hdb_cron_events
    ADD CONSTRAINT hdb_cron_events_pkey PRIMARY KEY (id);


pg_restore: creating CONSTRAINT "hdb_catalog.hdb_metadata hdb_metadata_pkey"
pg_restore: creating CONSTRAINT "hdb_catalog.hdb_metadata hdb_metadata_resource_version_key"
pg_restore: creating CONSTRAINT "hdb_catalog.hdb_scheduled_event_invocation_logs hdb_scheduled_event_invocation_logs_pkey"
pg_restore: from TOC entry 4777; 2606 103488 CONSTRAINT hdb_scheduled_event_invocation_logs hdb_scheduled_event_invocation_logs_pkey postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.hdb_scheduled_event_invocation_logs" does not exist
Command was: ALTER TABLE ONLY hdb_catalog.hdb_scheduled_event_invocation_logs
    ADD CONSTRAINT hdb_scheduled_event_invocation_logs_pkey PRIMARY KEY (id);


pg_restore: creating CONSTRAINT "hdb_catalog.hdb_scheduled_events hdb_scheduled_events_pkey"
pg_restore: from TOC entry 4780; 2606 103490 CONSTRAINT hdb_scheduled_events hdb_scheduled_events_pkey postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.hdb_scheduled_events" does not exist
Command was: ALTER TABLE ONLY hdb_catalog.hdb_scheduled_events
    ADD CONSTRAINT hdb_scheduled_events_pkey PRIMARY KEY (id);


pg_restore: creating CONSTRAINT "hdb_catalog.hdb_schema_notifications hdb_schema_notifications_pkey"
pg_restore: creating CONSTRAINT "hdb_catalog.hdb_version hdb_version_pkey"
pg_restore: from TOC entry 4785; 2606 103494 CONSTRAINT hdb_version hdb_version_pkey postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.hdb_version" does not exist
Command was: ALTER TABLE ONLY hdb_catalog.hdb_version
    ADD CONSTRAINT hdb_version_pkey PRIMARY KEY (hasura_uuid);


pg_restore: creating INDEX "hdb_catalog.event_invocation_logs_event_id_idx"
pg_restore: from TOC entry 4755; 1259 104098 INDEX event_invocation_logs_event_id_idx postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.event_invocation_logs" does not exist
Command was: CREATE INDEX event_invocation_logs_event_id_idx ON hdb_catalog.event_invocation_logs USING btree (event_id);


pg_restore: creating INDEX "hdb_catalog.event_log_created_at_idx"
pg_restore: from TOC entry 4758; 1259 104099 INDEX event_log_created_at_idx postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.event_log" does not exist
Command was: CREATE INDEX event_log_created_at_idx ON hdb_catalog.event_log USING btree (created_at);


pg_restore: creating INDEX "hdb_catalog.event_log_delivered_idx"
pg_restore: from TOC entry 4759; 1259 104100 INDEX event_log_delivered_idx postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.event_log" does not exist
Command was: CREATE INDEX event_log_delivered_idx ON hdb_catalog.event_log USING btree (delivered);


pg_restore: creating INDEX "hdb_catalog.event_log_locked_idx"
pg_restore: from TOC entry 4760; 1259 104101 INDEX event_log_locked_idx postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.event_log" does not exist
Command was: CREATE INDEX event_log_locked_idx ON hdb_catalog.event_log USING btree (locked);


pg_restore: creating INDEX "hdb_catalog.event_log_trigger_name_idx"
pg_restore: from TOC entry 4763; 1259 104102 INDEX event_log_trigger_name_idx postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.event_log" does not exist
Command was: CREATE INDEX event_log_trigger_name_idx ON hdb_catalog.event_log USING btree (trigger_name);


pg_restore: creating INDEX "hdb_catalog.hdb_cron_event_status"
pg_restore: from TOC entry 4768; 1259 104103 INDEX hdb_cron_event_status postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.hdb_cron_events" does not exist
Command was: CREATE INDEX hdb_cron_event_status ON hdb_catalog.hdb_cron_events USING btree (status);


pg_restore: creating INDEX "hdb_catalog.hdb_cron_events_unique_scheduled"
pg_restore: from TOC entry 4771; 1259 104104 INDEX hdb_cron_events_unique_scheduled postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.hdb_cron_events" does not exist
Command was: CREATE UNIQUE INDEX hdb_cron_events_unique_scheduled ON hdb_catalog.hdb_cron_events USING btree (trigger_name, scheduled_time) WHERE (status = 'scheduled'::text);


pg_restore: creating INDEX "hdb_catalog.hdb_scheduled_event_status"
pg_restore: from TOC entry 4778; 1259 104105 INDEX hdb_scheduled_event_status postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.hdb_scheduled_events" does not exist
Command was: CREATE INDEX hdb_scheduled_event_status ON hdb_catalog.hdb_scheduled_events USING btree (status);


pg_restore: creating INDEX "hdb_catalog.hdb_version_one_row"
pg_restore: from TOC entry 4783; 1259 104106 INDEX hdb_version_one_row postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.hdb_version" does not exist
Command was: CREATE UNIQUE INDEX hdb_version_one_row ON hdb_catalog.hdb_version USING btree (((version IS NOT NULL)));


pg_restore: creating FK CONSTRAINT "hdb_catalog.event_invocation_logs event_invocation_logs_event_id_fkey"
pg_restore: from TOC entry 4786; 2606 104653 FK CONSTRAINT event_invocation_logs event_invocation_logs_event_id_fkey postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.event_invocation_logs" does not exist
Command was: ALTER TABLE ONLY hdb_catalog.event_invocation_logs
    ADD CONSTRAINT event_invocation_logs_event_id_fkey FOREIGN KEY (event_id) REFERENCES hdb_catalog.event_log(id);


pg_restore: creating FK CONSTRAINT "hdb_catalog.hdb_cron_event_invocation_logs hdb_cron_event_invocation_logs_event_id_fkey"
pg_restore: from TOC entry 4787; 2606 104658 FK CONSTRAINT hdb_cron_event_invocation_logs hdb_cron_event_invocation_logs_event_id_fkey postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.hdb_cron_event_invocation_logs" does not exist
Command was: ALTER TABLE ONLY hdb_catalog.hdb_cron_event_invocation_logs
    ADD CONSTRAINT hdb_cron_event_invocation_logs_event_id_fkey FOREIGN KEY (event_id) REFERENCES hdb_catalog.hdb_cron_events(id) ON UPDATE CASCADE ON DELETE CASCADE;


pg_restore: creating FK CONSTRAINT "hdb_catalog.hdb_scheduled_event_invocation_logs hdb_scheduled_event_invocation_logs_event_id_fkey"
pg_restore: from TOC entry 4788; 2606 104663 FK CONSTRAINT hdb_scheduled_event_invocation_logs hdb_scheduled_event_invocation_logs_event_id_fkey postgres
pg_restore: error: could not execute query: ERROR:  relation "hdb_catalog.hdb_scheduled_event_invocation_logs" does not exist
Command was: ALTER TABLE ONLY hdb_catalog.hdb_scheduled_event_invocation_logs
    ADD CONSTRAINT hdb_scheduled_event_invocation_logs_event_id_fkey FOREIGN KEY (event_id) REFERENCES hdb_catalog.hdb_scheduled_events(id) ON UPDATE CASCADE ON DELETE CASCADE;


pg_restore: warning: errors ignored on restore: 28
Traceback (most recent call last):
	6: from /usr/local/bin/pgsync:23:in `<main>'
	5: from /usr/local/bin/pgsync:23:in `load'
	4: from /Library/Ruby/Gems/2.6.0/gems/pgsync-0.6.8/exe/pgsync:7:in `<top (required)>'
	3: from /Library/Ruby/Gems/2.6.0/gems/pgsync-0.6.8/lib/pgsync/client.rb:34:in `start'
	2: from /Library/Ruby/Gems/2.6.0/gems/pgsync-0.6.8/lib/pgsync/client.rb:25:in `perform'
	1: from /Library/Ruby/Gems/2.6.0/gems/pgsync-0.6.8/lib/pgsync/sync.rb:63:in `perform'
/Library/Ruby/Gems/2.6.0/gems/pgsync-0.6.8/lib/pgsync/schema_sync.rb:49:in `perform': Schema sync returned non-zero exit code (PgSync::Error)
```

**Comment by sasharevzin** [comment]
Yeah, doesn't work with `--all-schemas`. It's critical because Heroku [introduced](https://blog.testdouble.com/posts/2022-08-15-migrating-postgres-extensions-to-the-heroku_ext_schema/) `heroku_ext` schema with custom functions/extensions have been installed there.
