### ISSUE TITLE
Psych exception for aliases in Ruby 3.1.1

### ISSUE THREAD

**Issue by geoffharcourt** [ankane/pgsync#146]
Hello! I think there's a reasonable chance that this is actually a Psych problem, but I wanted to call it out since it was an unexpected issue for us. We're using pgsync 0.6.8.

After upgrading to Ruby 3.1.1 from 3.0.3, we are not able to use pgsync with a `.pgsync.yml` configuration file that contains YAML aliases. When we run outside debug, we get this error returned:

```
❯ pgsync curriculum,promotional --defer-constraints-v2
Unknown alias: matching_person_id_from_district
```

If we run with `--debug`, we get more information:

```
❯ pgsync curriculum,promotional --defer-constraints-v2 --debug
/Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias': Unknown alias: matching_person_id_from_district (Psych::BadAlias)
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych.rb:335:in `safe_load'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych.rb:370:in `load'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych.rb:671:in `block in load_file'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych.rb:670:in `open'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/psych.rb:670:in `load_file'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/pgsync-0.6.8/lib/pgsync/sync.rb:81:in `config'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/pgsync-0.6.8/lib/pgsync/sync.rb:18:in `block in perform'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/pgsync-0.6.8/lib/pgsync/sync.rb:17:in `each'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/pgsync-0.6.8/lib/pgsync/sync.rb:17:in `perform'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/pgsync-0.6.8/lib/pgsync/client.rb:25:in `perform'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/pgsync-0.6.8/lib/pgsync/client.rb:34:in `start'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/pgsync-0.6.8/exe/pgsync:7:in `<top (required)>'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/bin/pgsync:25:in `load'
        from /Users/geoff/.asdf/installs/ruby/3.1.1/bin/pgsync:25:in `<main>'
```

If we revert to Ruby 3.0.3 the issue goes away. The alias mentioned is present in our YAML, doesn't get referenced until after it's been defined, etc.

**Comment by ankane** [comment]
Hey @geoffharcourt, thanks for reporting! It looks like Psych 4 uses `safe_load` by default, which disables aliases unless `aliases: true` is passed.

**Comment by geoffharcourt** [comment]
You are so so fast, I was writing up a fix and you beat me to it.

**Comment by ankane** [comment]
Was a good report
