### ISSUE TITLE
Win10: Process.fork is not supported by this Ruby

### ISSUE THREAD

**Issue by chrismark** [ankane/pgsync#19]
Hi. I'm using win10, ruby 2.4.2p198, gem 2.6.13, pgsync 0.3.7.

I'm not able to do `pgsync --setup` to generate .yml file but copying an existing one seems to work fine. With the copied .yml file  (set to fetch from a remote server) am able to do `pgsync tablename --schema-only` but not `pgsync tablename` because it throws the ff. error:
```
Process.fork is not supported by this Ruby
* Syncing instrumentdata
<internal:prelude>:78:in `__read_nonblock': A non-blocking socket operation could not be completed immediately. - read would block (IO::EWOULDBLOCKWaitReadable)
        from <internal:prelude>:78:in `read_nonblock'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing/mutex.rb:66:in `block in locked?'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing.rb:26:in `handle_interrupt'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing.rb:26:in `try_handle_interrupt'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing/mutex.rb:64:in `locked?'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing/mutex.rb:117:in `block in unlock'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing.rb:26:in `handle_interrupt'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing.rb:26:in `try_handle_interrupt'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing/mutex.rb:116:in `unlock'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing/mutex.rb:141:in `block in synchronize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing.rb:26:in `handle_interrupt'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing.rb:26:in `try_handle_interrupt'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing/mutex.rb:133:in `synchronize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:162:in `block (3 levels) in sync_table'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:394:in `with_connection'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:145:in `block (2 levels) in sync_table'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:394:in `with_connection'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:144:in `block in sync_table'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:405:in `benchmark'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:143:in `sync_table'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:129:in `block in perform'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/parallel-1.12.0/lib/parallel.rb:486:in `call_with_index'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/parallel-1.12.0/lib/parallel.rb:318:in `block in work_direct'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/parallel-1.12.0/lib/parallel.rb:495:in `with_instrumentation'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/parallel-1.12.0/lib/parallel.rb:317:in `work_direct'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/parallel-1.12.0/lib/parallel.rb:260:in `map'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/parallel-1.12.0/lib/parallel.rb:217:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:572:in `in_parallel'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:128:in `perform'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/exe/pgsync:5:in `<top (required)>'
        from C:/Ruby24-x64/bin/pgsync:23:in `load'
        from C:/Ruby24-x64/bin/pgsync:23:in `<main>'
```

Anything that can be done with this?

Thanks for making great tool.

**Comment by ankane** [comment]
Hey @chrismark, thanks for reporting 👍  Please let me know if master works: https://github.com/ankane/pgsync#upgrading

**Comment by chrismark** [comment]
Hi @ankane. Thanks.

There's no more text that says 'Process.fork...' but still throws an error:
```
* Syncing instrumentdata
<internal:prelude>:78:in `__read_nonblock': A non-blocking socket operation could not be completed immediately. - read would block (IO::EWOULDBLOCKWaitReadable)
        from <internal:prelude>:78:in `read_nonblock'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing/mutex.rb:66:in `block in locked?'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing.rb:26:in `handle_interrupt'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing.rb:26:in `try_handle_interrupt'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing/mutex.rb:64:in `locked?'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing/mutex.rb:117:in `block in unlock'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing.rb:26:in `handle_interrupt'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing.rb:26:in `try_handle_interrupt'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing/mutex.rb:116:in `unlock'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing/mutex.rb:141:in `block in synchronize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing.rb:26:in `handle_interrupt'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing.rb:26:in `try_handle_interrupt'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multiprocessing-0.0.2/lib/multiprocessing/mutex.rb:133:in `synchronize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:159:in `block (3 levels) in sync_table'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:390:in `with_connection'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:142:in `block (2 levels) in sync_table'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:390:in `with_connection'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:141:in `block in sync_table'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:401:in `benchmark'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:140:in `sync_table'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:126:in `block in perform'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/parallel-1.12.0/lib/parallel.rb:486:in `call_with_index'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/parallel-1.12.0/lib/parallel.rb:342:in `block (2 levels) in work_in_threads'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/parallel-1.12.0/lib/parallel.rb:495:in `with_instrumentation'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/parallel-1.12.0/lib/parallel.rb:341:in `block in work_in_threads'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/parallel-1.12.0/lib/parallel.rb:206:in `block (2 levels) in in_threads'
```

**Comment by ankane** [comment]
Hey @chrismark, should be fixed now. Hopefully that will do it.

**Comment by chrismark** [comment]
Hi @ankane . Worked after a tiny change related to our remote db's password. It has an `@` sign and it's urlencoded into `%40` in the .pgsync.yml file.

So after installing from master, `pgsync table --schema-only` produces:
```
From: <db> on <remote>
To: <db> on <local>
* Dumping schema
pg_dump: [archiver (db)] connection to database "<db>" failed: FATAL:  password authentication failed for user "<username>"
pg_restore: [archiver] input file is too short (read 0, expected 5)
Completed in 2.2s
```
Thought something changed in db, but after trying out your previous change w/c worked, found out it has to do with added `shell_escape` in line 105 and 106 in pgsync.rb that's urlencoding the already urlencoded `@` sign.  Removed  `shell_escape` in my local copy and `pgsync table --schema-only`  worked but did notice this on the messages that appear on pg_restore:
```
....
pg_dump: saving encoding = UTF8
pg_dump: saving standard_conforming_strings = on
pg_restore: [archiver] did not find magic string in file header <<<
Completed in 21.8s
```
Created the table then ran `pgsync <table>` and it worked:
```
From: <db> on <remote>
To: <db> on <local>
* Syncing <table>
* DONE <table> (1.9s)
Completed in 3.0s
```

**Comment by ankane** [comment]
Looks like 0946f615b2a670069574933032441d3f2636fdea broke url encoding. I've reverted.
