### ISSUE TITLE
win10:  Bad file descriptor (Errno::EBADF) during pgsync --setup

### ISSUE THREAD

**Issue by chrismark** [ankane/pgsync#20]
Hi again @ankane . Forgot to include this error in my last post. Pops up during `pgsync --setup`

```
λ pgsync --setup
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych.rb:472:in `initialize': Bad file descriptor (Errno::EBADF)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych.rb:472:in `open'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych.rb:472:in `load_file'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:340:in `config'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:41:in `block in perform'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:40:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/lib/pgsync.rb:40:in `perform'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pgsync-0.3.7/exe/pgsync:5:in `<top (required)>'
        from C:/Ruby24-x64/bin/pgsync:23:in `load'
        from C:/Ruby24-x64/bin/pgsync:23:in `<main>'
```

**Comment by ankane** [comment]
Hey @chrismark, don't have any ideas on this one. Could use your help to debug.

**Comment by ankane** [comment]
Cleaning up issues. Let me know if you get a chance to debug.
