### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by HieronyM** [ankane/pgsync#219]
I got this error when trying to sync my source database (750 GB) to target RDS Aurora (the storage is autoscaling). I run this pgsync command `pgsync --all-schemas --schema-first --defer-constraints --overwrite --debug --fail-fast` in an EC2 instance, I also checked the disk and it's not full either. 

```
FROM STDIN
/home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pg-1.5.6/lib/pg/connection.rb:250:in `get_last_result': ERROR:  could not extend file "base/5212609/t10_6301516.9": wrote only 4096 of 8192 bytes at block 1275716 (PG::DiskFull)
HINT:  Check free disk space.
CONTEXT:  COPY pgsync_36449791, line 30702065
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pg-1.5.6/lib/pg/connection.rb:250:in `copy_data'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/task.rb:221:in `copy'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/task.rb:139:in `sync_data'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/task.rb:26:in `block (3 levels) in perform'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/task.rb:327:in `maybe_disable_triggers'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/task.rb:25:in `block (2 levels) in perform'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/task.rb:194:in `handle_errors'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/task.rb:24:in `block in perform'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/task.rb:182:in `with_notices'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/task.rb:23:in `perform'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/table_sync.rb:252:in `block (2 levels) in run_tasks'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/parallel-1.24.0/lib/parallel.rb:627:in `call_with_index'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/parallel-1.24.0/lib/parallel.rb:394:in `block in work_direct'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/parallel-1.24.0/lib/parallel.rb:637:in `with_instrumentation'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/parallel-1.24.0/lib/parallel.rb:393:in `work_direct'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/parallel-1.24.0/lib/parallel.rb:285:in `map'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/parallel-1.24.0/lib/parallel.rb:235:in `each'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/table_sync.rb:248:in `block in run_tasks'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/table_sync.rb:287:in `block (2 levels) in maybe_defer_constraints'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/data_source.rb:151:in `block in transaction'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pg-1.5.6/lib/pg/connection.rb:308:in `transaction'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/data_source.rb:150:in `transaction'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/table_sync.rb:286:in `block in maybe_defer_constraints'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/data_source.rb:151:in `block in transaction'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pg-1.5.6/lib/pg/connection.rb:308:in `transaction'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/data_source.rb:150:in `transaction'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/table_sync.rb:272:in `maybe_defer_constraints'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/table_sync.rb:244:in `run_tasks'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/table_sync.rb:28:in `perform'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/sync.rb:67:in `perform'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/client.rb:26:in `perform'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/lib/pgsync/client.rb:35:in `start'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/gems/pgsync-0.7.4/exe/pgsync:7:in `<top (required)>'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/bin/pgsync:23:in `load'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/bin/pgsync:23:in `<main>'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:24:in `eval'
	from /home/ec2-user/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:24:in `<main>'
```

Thank you

**Comment by ankane** [comment]
Hi @HieronyM, it looks like the error is coming from the database server (indicating that the disk is full).
