### ISSUE TITLE
--disable-user-trigger options results in "cannot ALTER TABLE 'some_table' because it has pending trigger events"

### ISSUE THREAD

**Issue by onwardmk** [ankane/pgsync#231]
```sh
createdb pgsync_from
createdb pgsync_to

psql pgsync_from << SQL
CREATE OR REPLACE FUNCTION public.audit_trigger_function()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
  DECLARE
    audit_id BIGINT := NEXTVAL('audit_id_seq');
    audit_diff JSONB := NULL;
    audit_request_context JSONB := CONNECTION_CONTEXT_JSON('request_context');
    audit_table TEXT := QUOTE_IDENT(TG_TABLE_NAME || '_audit');
    audit_sql TEXT := 'INSERT INTO ' || audit_table || ' SELECT $1, $2, NOW(), $3, $4, $5.*';
  BEGIN
    IF (TG_OP = 'INSERT') THEN
      EXECUTE audit_sql USING audit_id, 'I', audit_diff, audit_request_context, NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
      audit_diff := (ROW_TO_JSON(OLD.*)::JSONB @<> ROW_TO_JSON(NEW.*)::JSONB) - '{updated_at}'::TEXT[];
      EXECUTE audit_sql USING audit_id, 'U', audit_diff, audit_request_context, NEW;
    ELSIF (TG_OP = 'DELETE') THEN
      EXECUTE audit_sql USING audit_id, 'D', audit_diff, audit_request_context, OLD;
    END IF;

    RETURN NULL;
  END;
$function$

CREATE TABLE account_cancellation_reasons(
    id SERIAL NOT NULL,
    account_id bigint NOT NULL,
    cancellation_reason varchar NOT NULL,
    display_order integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fk_rails_f3d857eb3f FOREIGN key(account_id) REFERENCES accounts(id)
);
CREATE INDEX index_account_cancellation_reasons_on_account_id ON account_cancellation_reasons USING btree ("account_id");
CREATE UNIQUE INDEX index_cancellation_reasons_on_reason_and_account_id ON account_cancellation_reasons USING btree ("account_id","cancellation_reason");
CREATE TRIGGER accounts_audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.accounts FOR EACH ROW EXECUTE FUNCTION accounts_audit_function();

CREATE TRIGGER account_cancellation_reasons_audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.account_cancellation_reasons FOR EACH ROW EXECUTE FUNCTION audit_trigger_function();
SQL

psql pgsync_to << SQL
CREATE OR REPLACE FUNCTION public.audit_trigger_function()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
  DECLARE
    audit_id BIGINT := NEXTVAL('audit_id_seq');
    audit_diff JSONB := NULL;
    audit_request_context JSONB := CONNECTION_CONTEXT_JSON('request_context');
    audit_table TEXT := QUOTE_IDENT(TG_TABLE_NAME || '_audit');
    audit_sql TEXT := 'INSERT INTO ' || audit_table || ' SELECT $1, $2, NOW(), $3, $4, $5.*';
  BEGIN
    IF (TG_OP = 'INSERT') THEN
      EXECUTE audit_sql USING audit_id, 'I', audit_diff, audit_request_context, NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
      audit_diff := (ROW_TO_JSON(OLD.*)::JSONB @<> ROW_TO_JSON(NEW.*)::JSONB) - '{updated_at}'::TEXT[];
      EXECUTE audit_sql USING audit_id, 'U', audit_diff, audit_request_context, NEW;
    ELSIF (TG_OP = 'DELETE') THEN
      EXECUTE audit_sql USING audit_id, 'D', audit_diff, audit_request_context, OLD;
    END IF;

    RETURN NULL;
  END;
$function$

CREATE TABLE account_cancellation_reasons(
    id SERIAL NOT NULL,
    account_id bigint NOT NULL,
    cancellation_reason varchar NOT NULL,
    display_order integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fk_rails_f3d857eb3f FOREIGN key(account_id) REFERENCES accounts(id)
);
CREATE INDEX index_account_cancellation_reasons_on_account_id ON account_cancellation_reasons USING btree ("account_id");
CREATE UNIQUE INDEX index_cancellation_reasons_on_reason_and_account_id ON account_cancellation_reasons USING btree ("account_id","cancellation_reason");
CREATE TRIGGER account_cancellation_reasons_audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.account_cancellation_reasons FOR EACH ROW EXECUTE FUNCTION audit_trigger_function();

CREATE TRIGGER account_cancellation_reasons_audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.account_cancellation_reasons FOR EACH ROW EXECUTE FUNCTION audit_trigger_function();
SQL

pgsync --from pgsync_from --to pgsync_to
```

This is the output I see in the terminal when I run `pgsync --config pgsync.yml --defer-constraints --disable-user-triggers --debug`:
```sh
[to] SELECT tgname AS name, tgisinternal AS internal, tgenabled != 'D' AS enabled, tgconstraint != 0 AS integrity FROM pg_trigger WHERE pg_trigger.tgrelid = $1::regclass ["\"public\".\"account_cancellation_reasons\""]
[to] ALTER TABLE "public"."account_cancellation_reasons" DISABLE TRIGGER USER
[to] DELETE FROM "public"."account_cancellation_reasons"
[from] COPY (SELECT "public"."account_cancellation_reasons"."account_id", "public"."account_cancellation_reasons"."cancellation_reason", "public"."account_cancellation_reasons"."created_at", "public"."account_cancellation_reasons"."display_order", "public"."account_cancellation_reasons"."id", "public"."account_cancellation_reasons"."updated_at" FROM "public"."account_cancellation_reasons") TO STDOUT
[to] COPY "public"."account_cancellation_reasons" ("account_id", "cancellation_reason", "created_at", "display_order", "id", "updated_at") FROM STDIN
[from] SELECT last_value FROM "public"."account_cancellation_reasons_id_seq"
[to] SELECT setval('"public"."account_cancellation_reasons_id_seq"', '212')
[to] ALTER TABLE "public"."account_cancellation_reasons" ENABLE TRIGGER "account_cancellation_reasons_audit_trigger"
/home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/data_source.rb:142:in `exec_params': ERROR:  cannot ALTER TABLE "account_cancellation_reasons" because it has pending trigger events (PG::ObjectInUse)
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/data_source.rb:142:in `execute'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/task.rb:321:in `block (2 levels) in maybe_disable_triggers'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/task.rb:320:in `each'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/task.rb:320:in `block in maybe_disable_triggers'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/data_source.rb:156:in `transaction'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/task.rb:285:in `maybe_disable_triggers'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/task.rb:25:in `block (2 levels) in perform'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/task.rb:194:in `handle_errors'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/task.rb:24:in `block in perform'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/task.rb:182:in `with_notices'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/task.rb:23:in `perform'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/table_sync.rb:252:in `block (2 levels) in run_tasks'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/parallel-1.24.0/lib/parallel.rb:627:in `call_with_index'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/parallel-1.24.0/lib/parallel.rb:394:in `block in work_direct'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/parallel-1.24.0/lib/parallel.rb:637:in `with_instrumentation'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/parallel-1.24.0/lib/parallel.rb:393:in `work_direct'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/parallel-1.24.0/lib/parallel.rb:285:in `map'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/parallel-1.24.0/lib/parallel.rb:235:in `each'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/table_sync.rb:248:in `block in run_tasks'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/table_sync.rb:287:in `block (2 levels) in maybe_defer_constraints'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/data_source.rb:151:in `block in transaction'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pg-1.4.6/lib/pg/connection.rb:262:in `transaction'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/data_source.rb:150:in `transaction'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/table_sync.rb:286:in `block in maybe_defer_constraints'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/data_source.rb:151:in `block in transaction'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pg-1.4.6/lib/pg/connection.rb:262:in `transaction'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/data_source.rb:150:in `transaction'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/table_sync.rb:272:in `maybe_defer_constraints'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/table_sync.rb:244:in `run_tasks'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/table_sync.rb:28:in `perform'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/sync.rb:67:in `perform'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/client.rb:26:in `perform'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/lib/pgsync/client.rb:35:in `start'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/gems/pgsync-0.7.4/exe/pgsync:7:in `<top (required)>'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/bin/pgsync:25:in `load'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/bin/pgsync:25:in `<main>'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/bin/ruby_executable_hooks:22:in `eval'
        from /home/onwardmk/.rvm/gems/ruby-3.2.2@onward-system-api/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by ankane** [comment]
Hi @onwardmk, unfortunately, the script doesn't run (it references tables that don't exist). Please make sure the script is both self-contained and minimal if you're expecting support. https://en.wikipedia.org/wiki/Minimal_reproducible_example
