### ISSUE TITLE
Table name with capital letters.

### ISSUE THREAD

**Issue by shabbir21** [ankane/pgsync#25]
Executed command: `pgsync challengeTemplates --debug --overwrite`
Output: 

```
* Syncing challengeTemplates
/Library/Ruby/Gems/2.3.0/gems/pgsync-0.3.8/lib/pgsync.rb:438:in `exec_params': ERROR:  relation "challengetemplates" does not exist (PG::UndefinedTable)
	from /Library/Ruby/Gems/2.3.0/gems/pgsync-0.3.8/lib/pgsync.rb:438:in `primary_key'
	from /Library/Ruby/Gems/2.3.0/gems/pgsync-0.3.8/lib/pgsync.rb:232:in `block (3 levels) in sync_table'
	from /Library/Ruby/Gems/2.3.0/gems/pgsync-0.3.8/lib/pgsync.rb:391:in `with_connection'
	from /Library/Ruby/Gems/2.3.0/gems/pgsync-0.3.8/lib/pgsync.rb:143:in `block (2 levels) in sync_table'
	from /Library/Ruby/Gems/2.3.0/gems/pgsync-0.3.8/lib/pgsync.rb:391:in `with_connection'
	from /Library/Ruby/Gems/2.3.0/gems/pgsync-0.3.8/lib/pgsync.rb:142:in `block in sync_table'
	from /Library/Ruby/Gems/2.3.0/gems/pgsync-0.3.8/lib/pgsync.rb:402:in `benchmark'
	from /Library/Ruby/Gems/2.3.0/gems/pgsync-0.3.8/lib/pgsync.rb:141:in `sync_table'
	from /Library/Ruby/Gems/2.3.0/gems/pgsync-0.3.8/lib/pgsync.rb:127:in `block in perform'
	from /Library/Ruby/Gems/2.3.0/gems/pgsync-0.3.8/lib/pgsync.rb:569:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/pgsync-0.3.8/lib/pgsync.rb:569:in `in_parallel'
	from /Library/Ruby/Gems/2.3.0/gems/pgsync-0.3.8/lib/pgsync.rb:126:in `perform'
	from /Library/Ruby/Gems/2.3.0/gems/pgsync-0.3.8/exe/pgsync:5:in `<top (required)>'
	from /usr/local/bin/pgsync:22:in `load'
	from /usr/local/bin/pgsync:22:in `<main>'
```
I am able to sync all tables having names in lower case. As per the exception 

> relation "challengetemplates" does not exist

where as the table name is "challengeTemplates".

**Comment by ankane** [comment]
Hey @shabbir21, thanks for reporting 👍 Fixed on master.

```
gem install specific_install
gem specific_install https://github.com/ankane/pgsync.git
```

**Comment by shabbir21** [comment]
Cool, thank you !!
