### ISSUE TITLE
Not able to setup 

### ISSUE THREAD

**Issue by shabbir21** [ankane/pgsync#26]
Executed command: `pgsync --setup`

Exception printed:
```
/usr/lib/ruby/2.3.0/fileutils.rb:1392:in `initialize': No such file or directory @ rb_sysopen - /var/lib/gems/2.3.0/gems/pgsync-0.3.8/lib/pgsync/../config.yml (Errno::ENOENT)
	from /usr/lib/ruby/2.3.0/fileutils.rb:1392:in `open'
	from /usr/lib/ruby/2.3.0/fileutils.rb:1392:in `copy_file'
	from /usr/lib/ruby/2.3.0/fileutils.rb:486:in `copy_file'
	from /usr/lib/ruby/2.3.0/fileutils.rb:403:in `block in cp'
	from /usr/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
	from /usr/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
	from /usr/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
	from /usr/lib/ruby/2.3.0/fileutils.rb:402:in `cp'
	from /var/lib/gems/2.3.0/gems/pgsync-0.3.8/lib/pgsync/client.rb:195:in `setup'
	from /var/lib/gems/2.3.0/gems/pgsync-0.3.8/lib/pgsync/client.rb:54:in `perform'
	from /var/lib/gems/2.3.0/gems/pgsync-0.3.8/exe/pgsync:5:in `<top (required)>'
	from /usr/local/bin/pgsync:23:in `load'
	from /usr/local/bin/pgsync:23:in `<main>'
```

**Comment by ankane** [comment]
Hey @shabbir21, thanks for reporting 👍 Fixed now, but `master` is in the middle of refactor, so you may run into a number of errors until the next release.
