### ISSUE TITLE
Unable to update referenced row

### ISSUE THREAD

**Issue by ahmedmoazasif** [ankane/pgsync#37]
```
* Syncing user
    where id = 19398
/var/lib/gems/2.3.0/gems/pgsync-0.4.0/lib/pgsync/table_sync.rb:130:in `exec': ERROR:  update or delete on table "user" violates foreign key constraint "point_events_user_id_fkey" on table "point_events" (PG::ForeignKeyViolation)
DETAIL:  Key (id)=(19398) is still referenced from table "point_events".
        from /var/lib/gems/2.3.0/gems/pgsync-0.4.0/lib/pgsync/table_sync.rb:130:in `block in sync'
        from /var/lib/gems/2.3.0/gems/pgsync-0.4.0/lib/pgsync/table_sync.rb:129:in `transaction'
        from /var/lib/gems/2.3.0/gems/pgsync-0.4.0/lib/pgsync/table_sync.rb:129:in `sync'
        from /var/lib/gems/2.3.0/gems/pgsync-0.4.0/lib/pgsync/client.rb:95:in `block in sync'
        from /var/lib/gems/2.3.0/gems/pgsync-0.4.0/lib/pgsync/client.rb:264:in `each'
        from /var/lib/gems/2.3.0/gems/pgsync-0.4.0/lib/pgsync/client.rb:264:in `in_parallel'
        from /var/lib/gems/2.3.0/gems/pgsync-0.4.0/lib/pgsync/client.rb:94:in `sync'
        from /var/lib/gems/2.3.0/gems/pgsync-0.4.0/lib/pgsync/client.rb:24:in `perform'
        from /var/lib/gems/2.3.0/gems/pgsync-0.4.0/exe/pgsync:5:in `<top (required)>'
        from /usr/local/bin/pgsync:23:in `load'
        from /usr/local/bin/pgsync:23:in `<main>'
```

Attached is the error that is faced when trying to update rows that are referenced in other tables. This makes sense if the row was being deleted but it is just being updated,

**Comment by listenloop** [comment]
@ahmedmoazasif try again, this time with the --debug option. this will copy data serially and therefore you will not have this issue, provided your yml file lists the tables in the right order. like in your case `user` table should come before `point_events`

**Comment by jfanals** [comment]
@listenloop How do I specify the order of the tables on the yml file?

I have tried specifying it via the groups feature but that does not keep it in order.

**Comment by ykostsik** [comment]
@jfanals You need to user both of them, groups + --debug option. In this case it works serially and in the order you specified in the groups section.
