### ISSUE TITLE
Getting error on ruby 2.6.3 with pgsync

### ISSUE THREAD

**Issue by chemouna** [ankane/pgsync#70]
Hi, 

After installing pgsync gem , running pgsync i get the following error
```
Traceback (most recent call last):
	12: from /Users/mounacheikhna/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	11: from /Users/mounacheikhna/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	10: from /Users/mounacheikhna/.rvm/gems/ruby-2.6.3/bin/pgsync:23:in `<main>'
	 9: from /Users/mounacheikhna/.rvm/gems/ruby-2.6.3/bin/pgsync:23:in `load'
	 8: from /Users/mounacheikhna/.rvm/gems/ruby-2.6.3/gems/pgsync-0.4.3/exe/pgsync:4:in `<top (required)>'
	 7: from /Users/mounacheikhna/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /Users/mounacheikhna/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /Users/mounacheikhna/.rvm/gems/ruby-2.6.3/gems/pgsync-0.4.3/lib/pgsync.rb:5:in `<top (required)>'
	 4: from /Users/mounacheikhna/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /Users/mounacheikhna/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Users/mounacheikhna/.rvm/gems/ruby-2.6.3/gems/pg-1.2.2/lib/pg.rb:5:in `<top (required)>'
	 1: from /Users/mounacheikhna/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/mounacheikhna/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': incompatible library version - /Users/mounacheikhna/.rvm/gems/ruby-2.6.3/gems/pg-1.2.2/lib/pg_ext.bundle (LoadError)
	5: from /Users/mounacheikhna/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	4: from /Users/mounacheikhna/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	3: from /Users/mounacheikhna/.rvm/gems/ruby-2.6.3/bin/pgsync:23:in `<main>'
	2: from /Users/mounacheikhna/.rvm/gems/ruby-2.6.3/bin/pgsync:23:in `load'
	1: from /Users/mounacheikhna/.rvm/gems/ruby-2.6.3/gems/pgsync-0.4.3/exe/pgsync:3:in `<top (required)>'
/Users/mounacheikhna/.rvm/gems/ruby-2.6.3/gems/pgsync-0.4.3/exe/pgsync:6:in `rescue in <top (required)>': uninitialized constant PgSync (NameError)
```
Any pointers on how to fix this ? 

Thanks.

**Comment by ankane** [comment]
Hey @chemouna, it looks like an error with the pg gem.

```
incompatible library version - /Users/mounacheikhna/.rvm/gems/ruby-2.6.3/gems/pg-1.2.2/lib/pg_ext.bundle (LoadError)
```

Try reinstalling the pg gem:

```ruby
gem uninstall pg
gem install pg
```

**Comment by chemouna** [comment]
that worked, thanks a lot
