### ISSUE TITLE
How to fix "Table does not exist in source"?

### ISSUE THREAD

**Issue by jagerzhang** [ankane/pgsync#75]
Version 0.4.1
Sync  between different database in the same instance like：
```
pgsync table_test --from postgres://pgsync:pgsync@192.168.1.100:5432/db1 --to postgres://pgsync:pgsync@192.168.1.100:5432/db2 --to-safe --debug
```
Error info: 
```
From: db1 on 192.168.1.100:5432
To: db2 on 192.168.1.100:5432
Table does not exist in source: table_test
```

How can I solve it?

**Comment by ankane** [comment]
Hi @jagerzhang, pgsync doesn't sync the schema by default. Check out the readme for how to do that.

**Comment by jagerzhang** [comment]
@ankane Thank you for your reply.
Wrong report when run with --schema-first or --schema-only

```
* Dumping schema
Traceback (most recent call last):
        7: from /usr/local/bundle/bin/pgsync:23:in `<main>'
        6: from /usr/local/bundle/bin/pgsync:23:in `load'
        5: from /usr/local/bundle/gems/pgsync-0.4.1/exe/pgsync:5:in `<top (required)>'
        4: from /usr/local/bundle/gems/pgsync-0.4.1/lib/pgsync/client.rb:24:in `perform'
        3: from /usr/local/bundle/gems/pgsync-0.4.1/lib/pgsync/client.rb:88:in `sync'
        2: from /usr/local/bundle/gems/pgsync-0.4.1/lib/pgsync/client.rb:150:in `sync_schema'
        1: from /usr/local/bundle/gems/pgsync-0.4.1/lib/pgsync/data_source.rb:119:in `restore_command'
/usr/local/bundle/gems/pgsync-0.4.1/lib/pgsync/data_source.rb:119:in ``': No such file or directory - psql (Errno::ENOENT)
```

Line 119 of /usr/local/bundle/gems/pgsync-0.4.1/lib/pgsync/data_source.rb：
```
psql_version = `psql --version`.lines[0].chomp.split(" ")[-1].split(/[^\d.]/)[0]
```

Is this tool dependent on `pgsql`？ 

I run this tool in a docker container ，without `pgsql` ： [https://hub.docker.com/r/sandlerben/pgsync](https://hub.docker.com/r/sandlerben/pgsync)

**Comment by ankane** [comment]
Yeah, schema syncing uses/requires `psql`.

**Comment by jagerzhang** [comment]
Got it, Tks!
