### ISSUE TITLE
Syncing database between heroku environments

### ISSUE THREAD

**Issue by kbaum** [ankane/pgsync#90]
Hi. We are trying to sync data from one heroku environment to another running this command:

```
pgsync --schemas ourschema --disable-integrity --schema-first --to `heroku config:get HEROKU_POSTGRESQL_AQUA_URL -a sushi` --to-safe
```
But when end up the error:

```
el'
	10: from /Users/karlbaum/.gem/ruby/2.6.3/gems/pgsync-0.5.5/lib/pgsync/sync.rb:64:in `block in perform'
	 9: from /Users/karlbaum/.gem/ruby/2.6.3/gems/pgsync-0.5.5/lib/pgsync/table_sync.rb:13:in `sync'
	 8: from /Users/karlbaum/.gem/ruby/2.6.3/gems/pgsync-0.5.5/lib/pgsync/table_sync.rb:239:in `maybe_disable_triggers'
	 7: from /Users/karlbaum/.gem/ruby/2.6.3/gems/pgsync-0.5.5/lib/pgsync/data_source.rb:160:in `transaction'
	 6: from /Users/karlbaum/.gem/ruby/2.6.3/gems/pgsync-0.5.5/lib/pgsync/data_source.rb:160:in `transaction'
	 5: from /Users/karlbaum/.gem/ruby/2.6.3/gems/pgsync-0.5.5/lib/pgsync/data_source.rb:161:in `block in transaction'
	 4: from /Users/karlbaum/.gem/ruby/2.6.3/gems/pgsync-0.5.5/lib/pgsync/table_sync.rb:247:in `block in maybe_disable_triggers'
	 3: from /Users/karlbaum/.gem/ruby/2.6.3/gems/pgsync-0.5.5/lib/pgsync/table_sync.rb:247:in `each'
	 2: from /Users/karlbaum/.gem/ruby/2.6.3/gems/pgsync-0.5.5/lib/pgsync/table_sync.rb:249:in `block (2 levels) in maybe_disable_triggers'
	 1: from /Users/karlbaum/.gem/ruby/2.6.3/gems/pgsync-0.5.5/lib/pgsync/data_source.rb:154:in `execute'
/Users/karlbaum/.gem/ruby/2.6.3/gems/pgsync-0.5.5/lib/pgsync/data_source.rb:154:in `exec_params': PG::InsufficientPrivilege: ERROR:  permission denied: "RI_ConstraintTrigger_c_85543" is a system trigger (Parallel::UndumpableException)
```

Looks like we don't have permission to disable the constraint trigger on heroku?

Just for some context on how we ended up with this command. We are copying over the entire database beside a table or two we are excluding. When we run without `--disable-integrity` some of the sync fails because of foreign key constraints. I would rather not specify all of the tables in a specific order within the .pgsyc.yml file so disabling constraints felt like the right approach.

Let me know if I am missing something.
thx!

**Comment by ankane** [comment]
Hey @kbaum, based on the error message, it's a permissions issue.

**Comment by kbaum** [comment]
Gotcha. Is there a way around this besides specifying the insert order of every table? Thanks for your help!

**Comment by ankane** [comment]
The readme has a 3rd option you can try if you use deferrable constraints.
